# Generated by Django 5.0.6 on 2025-01-15 22:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescriptionModel',
            fields=[
                ('job_level_name', models.CharField(default=None, max_length=100)),
                ('job_tilte', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('job_description_id', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('job_description_upload_file', models.FileField(upload_to='job_descriptions/')),
                ('job_description_action', models.CharField(blank=True, default='active', max_length=60, null=True)),
                ('job_description_registration_date', models.DateTimeField(default=datetime.datetime(2025, 1, 16, 3, 49, 34, 432093))),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recruiter_job_desc_tb',
            },
        ),
        migrations.CreateModel(
            name='RecruiterBulkResumeUploadModel',
            fields=[
                ('recruiter_bulk_resume_upload_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('recruiter_bulk_resume_upload', models.FileField(blank=True, default=None, upload_to='recruiter_resumesUpload/')),
                ('recruiter_bulk_resume_upload_registration_date', models.DateTimeField(default=datetime.datetime(2025, 1, 16, 3, 49, 34, 433090))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recruiter_bulk_resume_upload_tb',
            },
        ),
        migrations.CreateModel(
            name='RecruiterResumeCandidateModel',
            fields=[
                ('recruiter_resume_candidate_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('recruiter_resume_candidate_file_path', models.TextField(blank=True, default=None, null=True)),
                ('recruiter_resume_candidate_extracted_text', models.TextField(blank=True, default=None, null=True)),
                ('recruiter_resume_candidate_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('recruiter_resume_candidate_gender', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('recruiter_resume_candidate_experience', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('recruiter_resume_candidate_nationality', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('recruiter_resume_tech_stack', models.CharField(blank=True, default=None, max_length=5000, null=True)),
                ('recruiter_resume_candidate_url', models.TextField(blank=True, default=None, null=True)),
                ('recruiter_resume_candidate_bookmark', models.BooleanField(default=False)),
                ('recruiter_resume_candidate_firstpage_image', models.FileField(blank=True, default=None, upload_to='resume_firstpage_images/')),
                ('recruiter_resume_candidate_ai_compare_score', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('recruiter_resume_candidate_registration_date', models.DateTimeField(default=datetime.datetime(2025, 1, 16, 3, 49, 34, 433090))),
                ('job_description', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recruiterAPI.jobdescriptionmodel')),
                ('recruiter_bulk_resume_upload', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recruiterAPI.recruiterbulkresumeuploadmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recruiter_resume_candidate_tb',
            },
        ),
    ]
