# Generated by Django 5.1.1 on 2024-10-04 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userloginAPI', '0003_alter_useremailverification_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremailverification',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 12, 9, 30, 686332)),
        ),
    ]
